name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './nas'

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GH_TOKEN}}
      
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/maoxian-1/save_doorbell_video:latest
        docker push ghcr.io/maoxian-1/save_doorbell_video:latest
